"""empty message

Revision ID: 1ac38a467175
Revises: 
Create Date: 2020-01-15 17:18:42.866232

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1ac38a467175'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'students', type_='foreignkey')
    op.drop_constraint(None, 'students', type_='foreignkey')
    op.create_foreign_key(None, 'students', 'divisions', ['current_division_id'], ['id'])
    op.create_foreign_key(None, 'students', 'teams', ['current_team_id'], ['id'])
    op.drop_column('students', 'division_id')
    op.drop_column('students', 'team_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('students', sa.Column('team_id', sa.INTEGER(), nullable=True))
    op.add_column('students', sa.Column('division_id', sa.INTEGER(), nullable=True))
    op.drop_constraint(None, 'students', type_='foreignkey')
    op.drop_constraint(None, 'students', type_='foreignkey')
    op.create_foreign_key(None, 'students', 'divisions', ['division_id'], ['id'])
    op.create_foreign_key(None, 'students', 'teams', ['team_id'], ['id'])
    # ### end Alembic commands ###
